### ISSUE TITLE
"loginWithHandler" cannot call back in iOS7

### ISSUE THREAD

**Issue by wuzhou** [Pocket/Pocket-ObjC-SDK#11]
I'm using this SDK on Xcode 5.1 for developing an APP(using ARC). 

And I use this method to authorize. When the program call this method it can redirect to the authorize web page and after click the "Authorize" button it can go back to the app. However, nothing happens after that. I am not login and and code in the block never be call. 

I also want to catch "PocketAPILoginFinishedNotification" by using NSNotificationCenter but don't success.

**Comment by liubko** [comment]
I paste this code in my `AppDelegate.m`
```
-(BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation{
  if([[PocketAPI sharedAPI] handleOpenURL:url]){
    NSLog(@"YES")
    return YES;
  }else{
    // if you handle your own URLs, do it here
    return NO;
  }
}
```

I receive the next url `pocketapp*****:authorizationFinished`, but I never reach inside loginWithHandler callback

```
  [[PocketAPI sharedAPI] loginWithHandler: ^(PocketAPI *API, NSError *error){
     NSLog(@"FINISHED")
  }];
```

@wuzhou could how you implemented `application openURL` function?
