### ISSUE TITLE
loginWithHandler never calls callback

### ISSUE THREAD

**Issue by liubko** [Pocket/Pocket-ObjC-SDK#17]
'm trying to login with pocket:

```
[[PocketAPI sharedAPI] loginWithHandler: ^(PocketAPI *API, NSError *error){
    NSLog(@"FINISHED")
}];
```

After this call, I'm being redirected to Pocket app, after I click "Authorize" button, I'm being redirected back to my app. But `NSLog(@"FINISHED");` had never been called.

Also in my `AppDelegate.m` I have this method:

```
-(BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation{
  if([[PocketAPI sharedAPI] handleOpenURL:url]){
    NSLog(@"YES, %@", url);
    return YES;
  }else{
    // if you handle your own URLs, do it here
    return NO;
  }
}
```

It gets called after I click on "Authorize" button, and I see `YES, pocketapp*****:authorizationFinished` in the console.

Why loginWithHandler callback never gets called?

**Comment by maicki** [comment]
Did you add a URL scheme for Pocket? See section "Add the Pocket URL scheme" in the documentation.

**Comment by liubko** [comment]
@maicki Yes I did, because if I put wrong url scheme it doesn't get redirected to app at all

**Comment by maicki** [comment]
@liubko Can you send us an email to api@getpocket.com . Let's trouble shoot via email and update this issue if we figured out what is going on.

**Comment by liubko** [comment]
It works! I downloaded and re-add SDK. Not sure what was the problem.

Maybe I screw up something while I was figuring out how to disable ARC.

@maicki thanks :+1:
