### ISSUE TITLE
access to acces_token

### ISSUE THREAD

**Issue by tzapu** [Pocket/Pocket-ObjC-SDK#18]
is there any way that we can use the iOS SDK for authentification and then get the access token whihc would allow us to fetch articles server side? would this be frowned upon as a way of doing things?

I know it works the other way around, the node.js lib for instance gives us the login url that we can use on the client side and then we can do the rest on the server side.

cheers

**Comment by maicki** [comment]
Currently it's not supported by default. You could expose the "pkt_getToken" method to the public in the PocketAPI class though

**Comment by tzapu** [comment]
thanks, exactly what i did
