### ISSUE TITLE
Getting saved values in PocketAPIKeychainUtils

### ISSUE THREAD

**Issue by mackinra** [Pocket/Pocket-ObjC-SDK#25]
@maicki: In the feature/extension-support branch, it appears that the following change (to include `accessGroup`) is warranted in   #`storeUsername:andPassword:forServiceName:inAccessGroup:updateExisting:error:`

```
--- a/SDK/PocketAPIKeychainUtils.m
+++ b/SDK/PocketAPIKeychainUtils.m
@@ -162,7 +162,7 @@ static NSString *PocketAPIKeychainUtilsErrorDomain = @"PocketAPIKeychainUtilsErr

 	// See if we already have a password entered for these credentials.
 	NSError *getError = nil;
-	NSString *existingPassword = [PocketAPIKeychainUtils getPasswordForUsername: username andServiceName: serviceName error:&getError];
+	NSString *existingPassword = [PocketAPIKeychainUtils getPasswordForUsername: username andServiceName: serviceName inAccessGroup:accessGroup error:&getError];

 	if ([getError code] == -1999) {
 		// There is an existing entry without a password properly stored (possibly as a result of the previous incorrect version of this code.
```

**Comment by maicki** [comment]
@mackinra Hey! I'm not working at Pocket anymore, but it seems @nzeltzer will gladly take over the repo and already has a fix up.

@nzeltzer As a side node - maybe would be worth it to get the `feature/extension-support` branch actually merged into master if there are no big conflicts.

**Comment by nzeltzer** [comment]
@maicki It looks like a clean merge. Talking this over is on my agenda today. Thanks for stopping in and providing some context!

**Comment by nzeltzer** [comment]
@mackinra This change has been merged, and feature/extension-support has been merged into master.

**Comment by mackinra** [comment]
@nzeltzer cool, thanks.
