### ISSUE TITLE
Remove SFHFKeychainUtils

### ISSUE THREAD

**Issue by romaonthego** [Pocket/Pocket-ObjC-SDK#3]
Hi Steve,

Could you please make SFHFKeychainUtils a dependency in cocoapods file and remove it from the SDK folder? As of right now, it results in Xcode warning "Multiple build commands for output file" when some other pods have SFHFKeychainUtils as their dependency.

**Comment by maicki** [comment]
Fixed in 1.0.3. SFHFKeychainUtils should not clash anymore if other pods have SFHFKeychainUtils as their dependency.
