### ISSUE TITLE
Operation queue is blocked after relogging

### ISSUE THREAD

**Issue by fastred** [Pocket/Pocket-ObjC-SDK#7]
Hi,
I've noticed that the handler block in `PocketAPI` `-callAPIMethod:withHTTPMethod:arguments:handler:` is not called after the user is successfully relogged. After further investigation I've found that `operationQueue` is blocked after relogging.

**Steps to reproduce:**

  1. Log in with `PocketAPI` `-loginWithHandler:`.
  2. Go to Connected Applications at getpocket.com and revoke access to the application.
  3. Call `-callAPIMethod:withHTTPMethod:arguments:handler:`.  `handler` block is called with the error 401, as expected.
  4. Redirect to Safari/Pocket is triggered. Click on "Authorize".
  5. Request from 3. should be re-run, but it's left in the `operationQueue` indefinitely. `po [[PocketAPI sharedAPI].operationQueue operations]` returns:
  
  ```
<__NSArrayM 0xb627080>(
<PocketAPIOperation: 0xb656b30 https://getpocket.com/v3get {
    count = 20;
    detailType = complete;
    since = 1384691485;
    sort = newest;
    state = all;
}>,
<PocketAPIOperation: 0xb5ab910 https://getpocket.com/v3get {
    count = 20;
    detailType = complete;
    since = 1384691485;
    sort = newest;
    state = all;
}>
)
  ```
  6. Further requests are also not processed because the operationQueue is blocked.

**Comment by maicki** [comment]
Fixed in 1.0.3
