### ISSUE TITLE
iOS App using Pocket-ObjC-SDK is rejected because of OAuth login with Safari.

### ISSUE THREAD

**Issue by shuitic** [Pocket/Pocket-ObjC-SDK#9]
My application which use Pocket API is rejected because of logging in with Safari.
**
Reasons

10.6: Apple and our customers place a high value on simple, refined, creative, well thought through interfaces. They take more work but are worth it. Apple sets a high bar. If your user interface is complex or less than very good it may be rejected
10.6

We found the following issues with the user interface of your app: The app opens a web page in mobile Safari for logging in, then returns the user to the app. The user should be able log in without opening Safari first.
**

I explained like this.
**
This application's target user has already had "Pocket" app which is free app. If they have "Pocket", they can login without Safari. Is this enough for this?
**

But they answered like this.
**
Thank you for your response regarding your app. However, we will still require login within the app.
**
What a silly reason this is.

I made pull request today. If you have a same problem, fork my solution.

**Comment by RyanCopley** [comment]
Why was this taken care of in private? What about other people could benefit from it too.

**Comment by Dids** [comment]
My app update was just rejected because of Pocket opening Safari to login. Previous updates have gone through just fine.

What's the deal here?

**Comment by shuitic** [comment]
Hi RayanCopley and Dids

There are nothing so much here. 
I changed Pocket API to be able to login without Safari,  and made my app through the Apple review.
See my pull request here.
https://github.com/Pocket/Pocket-ObjC-SDK/pull/10

Thanks!

**Comment by liubko** [comment]
If someone will decide to use solution by @shuitic, here is the ARC compatible SFHFKeychainUtils
https://stackoverflow.com/questions/7663443/sfhfkeychainutils-ios-keychain-arc-compatible/10348964#10348964

**Comment by bendodson** [comment]
Just in case this helps anyone, my app "Pocket Rocket" (https://dodoapps.io/pocket-rocket/) was also rejected because it used Safari for OAuth. I was told by Apple that I had to use their SFSafariViewController instead to keep users in the app. I personally think this is ridiculous as any built-in browser could be a spoof so the developer can capture the login details but apparently they don't really care about that. So, if you are building an app with the Pocket API, use SFSafariViewController
